const KEY_EXTERNAL_POLLUTED_API_AUTH_TOKEN = 'externalPollutedApiAuthToken';
const EXTERNAL_POLLUTED_API_AUTH_TOKEN_TTL = 60 * 60;

module.exports = {
  KEY_EXTERNAL_POLLUTED_API_AUTH_TOKEN,
  EXTERNAL_POLLUTED_API_AUTH_TOKEN_TTL,
};
